services:
  jenkins:
    image: jenkins-docker
    container_name: jenkins_compose
    user: root
    restart: always
    ports:
      - "9090:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://docker:2375
    depends_on:
      - docker

  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    command: ["--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock"]
    ports:
      - "2375:2375"
    volumes:
      - docker_data:/var/lib/docker

volumes:
  jenkins_home:
  docker_data: